name: ky_8r
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  get: 4.6.6
  flutter: 
    sdk: flutter
  freezed: ^2.4.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  hive_flutter: ^1.1.0



dev_dependencies: 
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  


flutter: 
  uses-material-design: true

